apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-backstage-scaffold
  annotations:
    github.com/project-slug: blackcatengineering/sample-backstage-scaffold
    backstage.io/techdocs-ref: blackcatengineering/sample-backstage-scaffold
spec:
  type: template
  lifecycle: unknown
  owner: admin
