apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: openstack-magnum-3tier-app
  title: OpenStack Magnum 3-Tier Application
  description: Scaffolds a 3-tier app with Kubernetes manifests ready for OpenStack Magnum CaaS.
  tags:
    - openstack
    - magnum
    - kubernetes
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: guest
  type: template

  parameters:
    - title: App Metadata
      required:
        - name
        - owner
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the 3-tier application.
        owner:
          title: Owner Group
          type: string
          description: The group that owns this component.
          default: engineering-group

    - title: Infrastructure & Routing Configuration
      required:
        - namespace
        - dbStorageSize
        - routingType
      properties:
        namespace:
          title: Kubernetes Namespace
          type: string
          default: default
        dbStorageSize:
          title: Database Volume Size (Gi)
          type: integer
          default: 10
        routingType:
          title: External Routing Strategy
          type: string
          default: Ingress
          enum:
            - Ingress
            - Octavia LoadBalancer

  steps:
    - id: fetch-base
      name: Fetch Template Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ values.name }}
          owner: ${{ values.owner }}
          namespace: ${{ values.namespace }}
          dbStorageSize: ${{ values.dbStorageSize }}
          routingType: ${{ values.routingType }}

    - id: publish
      name: Publish to Git Repository
      action: publish:github
      input:
        description: This is ${{ values.name }} hosted on OpenStack Magnum
        repoUrl: '://github.com/{{ values.name }}&owner=${{ values.owner }}'

    - id: register
      name: Register in Backstage Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
