apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{ values.name | dump }}
  description: 3-Tier Application running on OpenStack Magnum K8s.
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: {{ values.owner | dump }}
